# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "81da527cefdfa35c355f02893a2e383f"
name = "mira-discounts"
application_url = "https://mira-discounts-1e01191236ee.herokuapp.com/"
embedded = true
handle = "mira-discounts-1"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_discounts"

[auth]
redirect_urls = [
  "https://mira-discounts-1e01191236ee.herokuapp.com/auth/callback",
  "https://mira-discounts-1e01191236ee.herokuapp.com/auth/shopify/callback",
  "https://mira-discounts-1e01191236ee.herokuapp.com/api/auth/callback"
]

[pos]
embedded = false
