api_version = "2025-04"

[[extensions]]
name = "t:name"
handle = "b2b-75-percent-code-kits"
type = "function"
uid = "d66ddd07-e09a-871c-16e8-4baff0716cd426c2cc1d"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart-lines-discounts-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui]
  handle = "b2b-discount-ui"
