api_version = "2025-04"

[[extensions]]
name = "t:name"
handle = "b2b-75-percent-code-wands"
type = "function"
uid = "452ab841-d70a-ab03-4437-43b6003a7e0a01092cac"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart-lines-discounts-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui]
  handle = "b2b-discount-ui"
